default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1
  port: 3308

development:
  common:
    <<: *default
    database: rails_app_common_development
  common_replica:
    <<: *default
    database: rails_app_common_development
    replica: true
  school:
    <<: *default
    database: rails_app_school_development
  school_replica:
    <<: *default
    database: rails_app_school_development
    replica: true

# test:
#   <<: *default
#   database: multiple_db_sandbox_test
#
# production:
#   <<: *default
#   database: multiple_db_sandbox_production
#   username: multiple_db_sandbox
#   password: <%= ENV['MULTIPLE_DB_SANDBOX_DATABASE_PASSWORD'] %>
